name: 'Build docker cache'
description: 'Build docker container using a layer cache'
inputs:
  name:
    description: 'Unique name in this workflow (used for cache identification)'
    required: true
  context:
    description: 'Docker build context'
    default: '.'
  dockerfile:
    description: 'Dockerfile used for the build'
    default: 'Dockerfile'
  build-args:
    description: 'Dockerfile build arguments'
    default: ''
  target:
    description: 'Build target for multistage builds'
    required: true
  tag:
    description: 'Tag to add to the build container'
    required: true
  skip-setup:
    description: 'Skip setup of buildx. Useful if step is used more than once in one job.'
    default: false
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      if: !{{ inputs.skip-setup }}
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-${{ inputs.name }}
        # Key is named differently to avoid collision
        key: ${{ runner.os }}-multi-buildx-${{ inputs.name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx-${{ inputs.name }}

    - name: Build production image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        # Set the desired build target here
        target: ${{ inputs.target }}
        push: false
        load: true
        tags: ${{ inputs.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.name }}
        # Note the mode=max here
        # More: https://github.com/moby/buildkit#--export-cache-options
        # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-${{ inputs.name }}-new
        build-args: ${{ inputs.build-args }}
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache-${{ inputs.name }}
        mv /tmp/.buildx-cache-${{ inputs.name }}-new /tmp/.buildx-cache-${{ inputs.name }}
